name: Build Android APK

on:
  push:
    branches: [ "main" ]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # =======================================================
      # مرحله اصلاح شده اینجاست
      - name: Install dependencies
        run: npm install # <-- اینجا از ci به install تغییر کرد
      # =======================================================

      - name: Install Capacitor Android
        run: npx cap add android

      - name: Sync Capacitor
        run: npx cap sync

      - name: Accept Android SDK Licenses
        run: yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses || true

      - name: Build Android APK
        run: npx cap run android --no-sync -- -b assembleDebug

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pro-calc-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk